# Generated by Django 2.1.1 on 2018-10-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_point', models.CharField(blank=True, max_length=128, null=True)),
                ('connection_count', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Connections',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('asn', models.IntegerField(blank=True, null=True, unique=True)),
                ('total_peers', models.IntegerField(blank=True, null=True)),
                ('total_capacity', models.IntegerField(blank=True, null=True)),
                ('unique_orgs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeerOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('org', models.ManyToManyField(related_name='connections', through='execsite.Connectivity', to='execsite.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='connectivity',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execsite.Organization'),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='peer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execsite.PeerOrganization'),
        ),
    ]
